### ISSUE TITLE
Implement Glossarist reader plugin for Metanorma

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plugin-glossarist#1]
Metanorma should be able to read Glossarist datasets and import them as terms and definitions.

This plugin should have the following functionality:

1. Support loading of a Glossarist dataset (e.g. in YAML)
2. Selecting Glossarist concepts (from a Glossarist dataset) from the Metanorma document

e.g.

```adoc
= My document
:glossarist-dataset: dataset1;dataset2

...

== Terms and definitions

glossarist_entry::dataset1:concept-name[] // => creates terminology entry for "concept-name" here.

glossarist_entry::dataset1:*[] // => creates terminology entries for all dataset1 entries here.

```

**Comment by HassanAkbar** [comment]
From what I understand this will add 2 options
1. Like in `metanorma-plugin-datastruct`
```adoc
[glossarist,<content file>,<context name>]
----
== Concept {{<context name>.name}}
----
```
2. 
```adoc
= My document

:glossarist-dataset: dataset1;dataset2

== Terms and definitions

glossarist_entry::dataset1:concept-name[] // => creates terminology entry for "concept-name" here.

glossarist_entry::dataset1:*[] // => creates terminology entries for all dataset1 entries here.
```

@ronaldtse About option 2 can you explain how will the output look like? Or will there be a configurable template that we need to use?

**Comment by ronaldtse** [comment]
@HassanAkbar this is a great question!

Given a set of Concept YAML files, we want to:
1. Import the entire collection into the "Terms and definitions" clause
2. Filter some of those concepts in different separations of clauses, e.g. matching filter A in one clause, matching filter B in one clause
3. Only selecting one of those concepts

When we import a concept, we want to define a default template and allow a custom template.

Let me think about the syntax a bit...

**Comment by ronaldtse** [comment]
I think we will want to do something like this (we should refine the syntax).

## Load Glossarist datasets globally

```adoc
= My document
:glossarist-dataset: dataset1:./thispath/dataset1;dataset2:./thatpath/dataset2
```

## Import whole dataset collection

This automatically populates the terminology clause and bibliography sources.

```adoc
= My document
:glossarist-dataset: dataset1:./thispath/dataset1
glossarist:import[dataset1]
```

## Import only individual concepts

```adoc
= My document
:glossarist-dataset: dataset1:./thispath/dataset1;dataset2:./thatpath/dataset2

== Terms and definitions

=== Category one

glossarist::render[dataset1,my first term]
glossarist::render[dataset2,my second term]

=== Category two

glossarist::render[dataset1,my third term]
glossarist::render[dataset2,my four term]
...
```

## Import with filter and custom templates, using Liquid

When there is a defined dataset:
```
== Terms and definitions

// the following command imports the entire dataset using a custom template
// "context" is the handle of the context object given into Liquid
[glossarist,dataset1,filter='"lang=en"',context]
----
{% for concept in context %} 
=== {{concept.term.en}}

The definition is: "{{concept.definition.en}}"

{% if concept.source %}
[.source]
<<{{concept.source.anchor}}>>
{% endif %}
----
{% endfor %}
```

Add corresponding bibliography entries (because all the sources need to be listed in the bibliography):
```adoc
== Bibliography 

// the following command lists out all the bibliography sources and made unique
[glossarist,dataset1,filter='"lang=en",context]
----
{% assign sources = context | "filter out unique entries according to source.name" %} 
{% for source in sources %}
* [[[{{source.anchor}},{{source.short_name}}]]]
{% endfor %}
----
```

## Import single entry, automatically import term and add to bibliography

Cite a term entry:
```adoc
This cited {{glossarist:dataset1:ConceptId,glossarist concept entry}} is imported from dataset1.
```

## Questions...

Thoughts?

**Comment by HassanAkbar** [comment]
1. Import with filter and custom templates, using Liquid
2. Load Glossarist datasets globally
    ```adoc
    = My document
    :glossarist-dataset: dataset1:./thispath/dataset1;dataset2:./thatpath/dataset2
    ```
3. Import whole dataset collection
    ```adoc
    This automatically populates the terminology clause and bibliography sources.

    = My document
    :glossarist-dataset: dataset1:./thispath/dataset1
    glossarist:import[dataset1]
    ```
4. Import only individual concepts
    ```adoc
    = My document
    :glossarist-dataset: dataset1:./thispath/dataset1;dataset2:./thatpath/dataset2

    == Terms and definitions

    === Category one

    glossarist::render[dataset1,my first term]
    glossarist::render[dataset2,my second term]

    === Category two

    glossarist::render[dataset1,my third term]
    glossarist::render[dataset2,my four term]
    ```

Point 1 is clear but I have some questions related to other points.

**Questions**

- `:glossarist-dataset: dataset1:./thispath/dataset1;dataset2:./thatpath/dataset2` This will only load the `dataset1` and will not do any rendering.
- What will be the difference between `glossarist:import` and `glossarist::render`?

**Comment by ronaldtse** [comment]
> * `:glossarist-dataset: dataset1:./thispath/dataset1;dataset2:./thatpath/dataset2` This will only load the `dataset1` and will not do any rendering. Is my understanding correct?

Correct. This attempts to assign the handle `dataset1` to the concept dataset of `./thispath/dataset1` and the handle `dataset2` to the concept dataset at `./thatpath/dataset2`.

The handles can be subsequently referred to in the document.

> * What will be the difference between `glossarist:import` and `glossarist::render` in point 3 and 4?

We actually want actually three separate actions:
* Declare/Load: make a concept available for reference within the document but do not render. (the `:glossarist-dataset:` attribute)
* Render: render a single concept inside the document. (the `glossarist:render` command)
* Import/Render all: add all concepts from the dataset into the document. (the `glossarist:import` command)

(I am unsure whether we need to have one or two colons for these commands).

## Render a single concept

Typically, "rendering 1 concept" from the concept dataset into the Metanorma concept format like this template (let's call this `concept.adoc.liquid`) is simple.

concept.adoc.liquid:
```adoc
==== concept term
alt:[if additional terms]

definition text

NOTE: if there is a note.

[example]
If there is an example.

[.source]
<<If there is some source>>
```

But it is not as simple as just rendering the concept into a template:
* If the concept contains a bibliographic source, we need to add that bibliographic source needs to be added into the Metanorma document as well. That requires insertion of the bibliographic sources (Relaton objects?) into the Metanorma document object. 


## Importing a concept dataset

`glossarist:import` aims to "import all concepts" from the concept dataset. 

There are a few things it needs to do:
1. Generate the contents of the "terms and definitions" section
2. Add all bibliographic sources of the concepts dataset into the Metanorma document

Updated syntax:
```adoc
= My document
:glossarist-dataset: dataset1:./thispath/dataset1

== Terms and definitions
glossarist:import[dataset1]
```

The `glossarist:import` command would do something like this:
```adoc
{% foreach concept in glossarist.concepts %}

{% render concept.adoc.liquid, local: concept %}

{% endfor %}
```

And add the bibliographic sources from the concepts dataset into the document (unique references/anchors, of course)

**Comment by ronaldtse** [comment]
> **Questions**
> 
> * There are 2 types of sources in glossarist `authoritative` and `lineage`. Should we only include `authoritative` sources in bibliographies or all sources?

Right now let's not differentiate them.

> * Do we need to add all the bibliographies for loaded concepts through `:glossarist-dataset: dataset1:./thispath/dataset1;dataset2:./thatpath/dataset2` or only the bibliographies for `rendered` and `imported` concepts?

Only for the `rendered` and `imported` concepts.

Thanks.

**Comment by HassanAkbar** [comment]
@ronaldtse according to the following blog https://www.metanorma.org/author/topics/document-format/bibliography/, there are 3 different ways to define bibliography section
1. `[bibliography]` tag
2. `[bibliography,normative=false]` tag
3. `== Bibliography` followed by multiple subsections, e.g
    ```adoc
    == Bibliography

    [bibliography]
    === Part 1
    
    * [[[id1,1]]] _First reference_
    * [[[id2,2]]] _Second reference_
    * [[[id3,3]]] _Third reference_
    
    [bibliography]
    === Part 2
    
    * [[[id4,4]]] _Fourth reference_
    * [[[id5,5]]] _Fifth reference_
    * [[[id6,6]]] _Sixth reference_
    ```

**Questions**

- For `1` and `2` we can add the bibliographies at the start or at the end of the section but for `3` in which subsection should we add the bibliographies? Should we add them at the start of the first subsection or last subsection or create a new subsection?

**Comment by ronaldtse** [comment]
@HassanAkbar Re: the 3 types of defining a bibliography section:

The Glossarist plugin should NOT define a bibliography section (because the author defines where the entries go into), but provide a method to "fill in the bibliographic entries".

i.e.
```adoc
== Bibliography  (<<< this line is defined by the author)
glossarist:import_bibliography[dataset1]
```

=>
```adoc
== Bibliography  (<<< this line is defined by the author)

// the following lines are generated by the Glossarist plugin
* [[[id1,1]]] _First reference_
* [[[id2,2]]] _Second reference_
* [[[id3,3]]] _Third reference_
```

Another example:
```adoc
== Bibliography  (<<< this line is defined by the author)
=== Subsection 1  (<<< this line is defined by the author)
glossarist:import_bibliography[dataset1]
```

=>
```adoc
== Bibliography  (<<< this line is defined by the author)
=== Subsection 1  (<<< this line is defined by the author)

// the following lines are generated by the Glossarist plugin
* [[[id1,1]]] _First reference_
* [[[id2,2]]] _Second reference_
* [[[id3,3]]] _Third reference_
```

**Comment by HassanAkbar** [comment]
```asciidoc
== Terms and definitions

// the following command imports the entire dataset using a custom template
// "context" is the handle of the context object given into Liquid
[glossarist,dataset1,filter='"lang=en"',context]
----
{% for concept in context %} 
=== {{concept.term.en}}

The definition is: "{{concept.definition.en}}"

{% if concept.source %}
[.source]
<<{{concept.source.anchor}}>>
{% endif %}
----
{% endfor %}
```

Hi @ronaldtse , I'm almost done with this task, just wanted to make sure what is the function of the filters in the above example. So I have the following questions
- In the above example there is a filter for `lang=en` what will that do? 
- What other filters can the user add?

**Comment by HassanAkbar** [comment]
Ping @ronaldtse

**Comment by ronaldtse** [comment]
@HassanAkbar sorry for the delay. 

The purpose of the "filter" is to find concept entries that matches the filter. For example, `lang=en` is meant to match English entries only.

The types of available filters should be defined by the Glossarist plugin. For example, these filters can be possible:

* publishing status of a concept (e.g. "published", "draft")
* source of the concept (e.g. from document "ISO 44001:2019")
* type of the term (e.g. is an abbreviation, has a deprecated term)

As long as it is easy to extend in the future it's good enough. We do not need to implement all these now.
