### ISSUE TITLE
Provide method to define sorting order

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plugin-glossarist#21]
Once https://github.com/glossarist/glossarist-ruby/issues/86 is implemented.

**Comment by HassanAkbar** [comment]
@ronaldtse `sort_by` filter is already implemented. Here is an example -> https://github.com/metanorma/metanorma-plugin-glossarist/blob/main/spec/metanorma/plugin/glossarist/dataset_preprocessor_spec.rb#L84 

Is there anything else that we need to add to this?

**Comment by ronaldtse** [comment]
@HassanAkbar can you update documentation so users can know how to use it?

**Comment by ronaldtse** [comment]
Thanks!
