### ISSUE TITLE
Add GHA release flow, adopt from other metanorma gems

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plugin-glossarist#3]
Metanorma gem repositories come with a GHA workflow for automatic release. We should adopt that workflow here so the metanorma Rubygems user can directly publish gems.

**Comment by suleman-uzair** [comment]
Do I need to add the ```GHA``` through ```CIMAS``` or can I write them manually by using the shared workflows in **```metanorma-build-scripts```**?

**Comment by ronaldtse** [comment]
I believe we can just do them manually. Ping @camobap for advice.
